version: 0.1

mysql:
  host: 'localhost'
  port: 3306
  user: 'root'
  database: 'database'
  password: ''
  minimumConnections: 2
  maximumConnections: 5
  timeout: 3500

motd:
  - "XD"
  - "2"

nabor: "https://bit.ly/su_nabor"
maintenance: false
season: "halloween"

halloween_join:
  - "%player% prišiel všetkých vyspookovať!"
  - "%player% sa pripojil a prišiel vás vystrašiť!"
  - "%player% nezabudol na najlepší sviatok v roku, až po Vianociach, kek."

halloween_quit:
  - "%player% došli cukríky tak to už vzdal."
  - "%player% si išiel prepúdrovať svoj halloween kostým, asi."
  - "%player% bol strašne vyspookovaný tak zdrhol."