name: SurvCore
version: 1.1.0-${git.commit.id.abbrev}
main: sk.ignissak.su.survcore.Core
authors: [iGniSsak]
load: STARTUP
commands:
  su:
    description: Hlavny prikaz
    usage: /su
  sethome:
    description: Nastavenie home
    usage: /sethome
  home:
    description: Teleportace na home
    usage: /home
  delhome:
    description: Vymazanie homu
    usage: /delhome
  gc:
    description: Statistiky vykonu serveru
    usage: /lag
    aliases: [lag]
  playtime:
    description: Informacie o playtime
    usage: /playtime
    aliases: [pt]
  ping:
    description: Informacie o pingu
    usage: /ping
  overit:
    description: Prepojenie uctov
  odpojit:
    description: Odpojenie uctu
  version:
    description: Verzia serveru
    aliases: [verzia]
  spawn:
    description: Spawn sveta
  seen:
    description: Zistenie kedy bol hrac naposledy online
  vanish:
    description: Incognito pre adminov XD
  msg:
    description: Sukromne spravy
    aliases: [tell, whisper, m]
  maintenance:
    description: Udrzba